meta_product_name: "Mecha Industries"
meta_title: "Mecha Industries - All in One NFT Launchpad"
meta_description: "Mint, Launch and List Your NFT Collection. We do everything you only provide the Art."
meta_image: "cover.png" # should exist in `app/assets/images/`
twitter_account: "MechaApeLabs"   # required for Twitter Cards
